version: '3.8'
services:
  db:
    image: mysql:5.7.40
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=hoidanit
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'